### ISSUE TITLE
Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by theasder** [jamesturk/django-secretballot#31]
Used the latest version of django-secretballot, django v.1.9.5, used python3 and it raises an error after launching server

	Internal Server Error: /
	Traceback (most recent call last):
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/django/core/handlers/base.py", line 123, in get_response
	    response = middleware_method(request)
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/secretballot/middleware.py", line 6, in process_request
	    request.secretballot_token = self.generate_token(request)
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/likes/middleware.py", line 19, in generate_token
	    return md5(s).hexdigest()
	TypeError: Unicode-objects must be encoded before hashing

**Comment by jamesturk** [comment]
It looks like you're using a middleware in a different package? likes.middleware

The included middleware does call encode.
