### ISSUE TITLE
AttributeError: object has no attribute 'total_upvotes'

### ISSUE THREAD

**Issue by theasder** [jamesturk/django-secretballot#32]
Without Ajax it worked well, but with ajax:

Internal Server Error: /likes/like/interview_questions-problem/23/1
	Traceback (most recent call last):
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/django/template/base.py", line 883, in _resolve_lookup
	    current = current[bit]
	TypeError: 'Problem' object is not subscriptable

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
	    response = self.process_exception_by_middleware(e, request)
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
	    response = wrapped_callback(request, *callback_args, **callback_kwargs)
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/likes/views.py", line 49, in like
	    "content_type": url_friendly_content_type,
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/secretballot/views.py", line 66, in vote
	    body = t.render(c)
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/django/template/backends/django.py", line 95, in render
	    return self.template.render(context)
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/django/template/base.py", line 206, in render
	    return self._render(context)
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/django/template/base.py", line 197, in _render
	    return self.nodelist.render(context)
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/django/template/base.py", line 992, in render
	    bit = node.render_annotated(context)
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
	    return self.render(context)
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/django/template/defaulttags.py", line 326, in render
	    return nodelist.render(context)
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/django/template/base.py", line 992, in render
	    bit = node.render_annotated(context)
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
	    return self.render(context)
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/django/template/base.py", line 1043, in render
	    output = self.filter_expression.resolve(context)
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/django/template/base.py", line 709, in resolve
	    obj = self.var.resolve(context)
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/django/template/base.py", line 850, in resolve
	    value = self._resolve_lookup(context)
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/django/template/base.py", line 891, in _resolve_lookup
	    current = getattr(current, bit)
	  File "/Users/artemdremov/Documents/python/interview_project/venv/interview_project/lib/python3.4/site-packages/secretballot/__init__.py", line 43, in get_total
	    return getattr(self, upvotes_name) - getattr(self, downvotes_name)
	AttributeError: 'Problem' object has no attribute 'total_upvotes'

secretballot v.0.5.0
Django 1.9.5
Python 3

**Comment by hedleyroos** [comment]
I fixed it in https://github.com/jamesturk/django-secretballot/pull/29. Waiting on @jamesturk  to merge it.

**Comment by jamesturk** [comment]
sorry about the delay & thanks for the PR, just merged it.  @theasder can you confirm that this fixes your problem as well?

**Comment by jamesturk** [comment]
going to assume this is fixed as it looks like the same issue, closing this. please reopen if unresolved
